### ISSUE TITLE
Mqtt support

### ISSUE THREAD

**Issue by pavel-ch** [shroffk/phoebus#240]
Does Phoebus support mqtt:// data source atm.? Thank you.

**Comment by pavel-ch** [comment]
Thank you. No hurry, a question only for now. What payload standard are you using (again, no full info, a hint is enough)? Thanks.

**Comment by kasemir** [comment]
Part of the work would be to document that in a short readme @es-sns121 , since we didn't really explain that for the previous implementation.

We expect all traffic to go through one broker, so there's a preference setting for the mqtt broker URL:

`some.package.name/mqtt_broker=tcp://my_mqtt_broker_host.site.org:1883`

We'll develop with Mosquitto as the broker.

PV names are then like `mqtt://some/topic/name`, like `mqtt://tank/level` or `mqtt://tank/temperature`.
Since the broker URL is a preference, there's no need to duplicate the broker URL in each PV, which would make for really long PV names. 

The problem with MQTT is of course that the data could be anything. We are not handling arbitrary JSON or the like. We expect the value to be a simple string that usually holds a number, like "20.5".

To be a little more flexible, the PV name can include the expected type:
`mqtt://tank/level<VDouble>` will try to parse a double from the value text.
`mqtt://tank/level<VLong>` will try to parse a long from the value text.
`mqtt://tank/state<VString>` will read the value text as a string.
`mqtt://tank/state<VEnum>(0, "A", "B", "C")` will try to obtain an enumerated value from the value text.

So the format is a bit like the `loc://` PVs with type & value initializer.

When writing to a PV, we write the string version of the data as a 'retained' MQTT message.
There's really no support for "write callback" aka "completion": MQTT has so called qualilty-of-service, but that basically just tells you that the written data arrived. What you need in the real world is confirmation that the data arrived, something was done about it, and that completed. For example, a desired motor position was received, the motor was moved, and the motor reached that position. MQTT doesn't offer that, so we can't implement it.

**Comment by pavel-ch** [comment]
Ok, I understand, good starting point later then. Thank you.
