### ISSUE TITLE
Alarm Logging UI: Missing dependency and preference setting error

### ISSUE THREAD

**Issue by tanviash** [shroffk/phoebus#514]
Alarm Logging-UI preference settings through settings.ini for es_host doesn't work. Also, logging-ui package as a dependency is missing from phoebus-product/pom.xml.

**Comment by kasemir** [comment]
It's currently easy to remove functionality from a product (delete the jar file) but a little harder to add (need to build the jar file, add it, _and_ add that jar file to the classpath products manifest).
That's why I include the alarm UI in the SNS product, and then delete the jars in most installations.
I'm OK with similarly including the alarm UI in the default product.

**Comment by tanviash** [comment]
@shroffk Let me know if we are adding the alarm-logging-ui dependency to default product as Kay mentioned above or going the individual site specific way.

**Comment by shroffk** [comment]
This has been added.
