### ISSUE TITLE
Email structure for Alarm notifications

### ISSUE THREAD

**Issue by tanviash** [shroffk/phoebus#643]
@kasemir @shroffk @berryma4 
Currently, this is how the alarm notification looks like when it is received in the email.
/Accelerator/Test-node sim://noise
Description: sim://noise
Alarm Time: 2019-04-08 10:12:10.678
Alarm Severity: MAJOR, Status: LOLO, Value: -4.426769311920065 Current PV Severity: MAJOR, Status: LOLO

One thing I notice is Status is repeated twice. Also, I have received feedback from operator manager that Current Timestamp is not included and is an important data for them. Is it possible to get it included in the alarm notification? Also, can we modify this message such that current alarm severity, current status and current timestamp comes before the alarm severity , status & value? So the message looks something like.
 /Accelerator/Test-node sim://noise
Description: sim://noise
Current Alarm Time:
Current PV Severity: MAJOR, Current Status: LOLO
Alarm Time: 2019-04-08 10:12:10.678
Alarm Severity: MAJOR, Status: LOLO, Value: -4.426769311920065 

Please let me know your thoughts. If you all are fine, I can work on the fix and submit pull request.

**Comment by kasemir** [comment]
> Status is repeated twice. 

They're different. One is part of alarm state, the other for current PV info.

> can we modify this message such that...

I picked that format after looking at the resulting email in a desktop email client as well as a phone, and decided to go with concise, placing most of the alarm state on one line, and using just "Status" instead of "The status that belongs to the (potentially latched) alarm state" vs. "Last received status from the PV".

If  you prefer a more verbose formar, one item per line, fine.
Please create pull request.

Whatever we do, nobody will ever be really happy until we add a scripting interface that allows each site to create their own format, but I'd like to avoid that.

> current timestamp
That's not held in the alarm model (org.phoebus.applications.alarm.model.AlarmState). It's not relevant to determining the alarm state, and to end users the value would basically be 'now'. So right now you can't easily add that to the message. End users can check the date/time of the email.
