### ISSUE TITLE
Error Log application

### ISSUE THREAD

**Issue by pavel-ch** [shroffk/phoebus#947]
New lines added after app startup are higher than necessary. Platform: Windows 10. See screenshot.
![obrazek](https://user-images.githubusercontent.com/771816/68966367-33b73400-07de-11ea-8ecf-7851d13a4df5.png)

**Comment by kasemir** [comment]
Interesting. I don't see that on Linux. The code doesn't try to do anything about the row height, it just sets the text and for stderr messages the color.
Could this be caused by `\r` in the text? We split lines on `\n`, so that's removed. ... and maybe empty lines should be skipped in the errolog, but that's a different issue.

Can you add code to remove `\r` from the text, like in `LineView.addLine()` to see if some `\r` in the text causes the change in row height?

**Comment by kasemir** [comment]
Yes, must be `\r`, because when I add that on Linux I also get higher rows.
Try this in LineDetectingOutputInterpose.java:
```
--- a/app/errlog/src/main/java/org/phoebus/applications/errlog/LineDetectingOutputInterpose.java
+++ b/app/errlog/src/main/java/org/phoebus/applications/errlog/LineDetectingOutputInterpose.java
@@ -71,6 +71,10 @@ public class LineDetectingOutputInterpose extends OutputStream
             line_handler.accept(new String(linebuf, 0, count));
             count = 0;
         }
+        else if (b == '\r')
+        {
+            // Skip Windows line feed
+        }
         else
         {
```

**Comment by kasemir** [comment]
Please try the latest on windows, should be OK.

**Comment by pavel-ch** [comment]
I can confirm that you were right with the \r on Windows platform, the effect has gone. Hope Mac is ok now, too. Thanks

**Comment by kasemir** [comment]
Mac is unhappy because the app is not downloaded from the Apple App Store, but the errlog seems fine.
Thanks for confirming state on Windows!
